version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    volumes:
      - ./web:/usr/share/nginx/html
  db:
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: secret
       MYSQL_DATABASE: laravel
